### ISSUE TITLE
Summary code is not applicable to to YAS data

### ISSUE THREAD

**Issue by MadinaHasan19** [CUREd-Plus/cuRed#209] opened 2024-01-19 09:43 UTC
The problem is in this particular line
> column_counts <- table(sapply(data, class))
Error in table(sapply(data, class)) : 
  all arguments must have the same length

When investigating it I found that some fields have multiple data types due to having two items in a single cell. For example: see $timestampt1

$date_time_forperf
[1] "POSIXct" "POSIXt" 

$timestampt0
[1] "POSIXct" "POSIXt" 

$timestampt1
[1] "POSIXct" "POSIXt" 

$timestampt2
[1] "POSIXct" "POSIXt" 

$timestampt3
[1] "POSIXct" "POSIXt" 

$timestampt4
[1] "POSIXct" "POSIXt" 

$mainpatientage
[1] "character"

$mainpatientsex
[1] "character"

$chiefcomplaint
[1] "character"

$perfbestresp
[1] "POSIXct" "POSIXt" 

$perfbestlatepatside
[1] "POSIXct" "POSIXt" 

$methodofcall
[1] "character"

**Comment by Joe-Heffer-Shef** [comment] 2024-01-19 11:44
Are we talking about this code?
https://github.com/CUREd-Plus/cuRed/blob/issue-28/summary/R/summary.R

**Comment by Joe-Heffer-Shef** [comment] 2024-01-22 10:35
It looks like the problem is that the Parquet `[timestamp](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#timestamp)` data type is converted to the R data type `[1] "POSIXct" "POSIXt"`. The error `all arguments must have the same length` might mean that this data type is a vector with length 2?

https://github.com/CUREd-Plus/cuRed/blob/3c6082a1fbb85868a4772daec05e7e8fd69693be/R/summary.R#L63
```R
column_counts <- table(sapply(data, class))
```

Is there another function we can use to more efficiently get the metadata without writing our own code?

e.g. https://arrow.apache.org/docs/r/articles/metadata.html
or https://github.com/CUREd-Plus/cuRed/blob/9db87f819d22c4059f3d46c4885c3d3aaf65a48d/R/read_parquet.R#L29

(This is a separate issue, but how does `sapply` work here? Does it apply the `class` function to every value in the data set?)

**Comment by MadinaHasan19** [comment] 2024-01-22 10:38
Yes, it applies the class function to each column in the data

**Comment by G-Accad** [comment] 2024-02-12 13:36
Updated the summary code to take it into account, will close this issue now

**Closed** 2024-02-12 13:36 UTC
